name: github notification

on:
  pull_request:
    types: [closed]

jobs:
  pull_request_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Need to incorporate changes
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "ぎっとはぶちゃん"
          message: "
[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})\n
のマージを完了しました。mainの内容を各ブランチへ取り込んでおいてください
"